[
  {
      "id": "1",
      "name": "Punisher",
      "artist": "Phoebe Bridgers",
      "totalTracks": "11",
      "price": "",
      "albumImg": "https://i.scdn.co/image/ab67616d0000b273a91b75c9ef65ed8d760ff600",
      "releaseDate": "2020-06-18",
      "genre": "alternative",
      "label": "Dead Oceans"
  },
  {
      "id": "2",
      "name": "Philharmonics (Deluxe Edition)",
      "artist": "Agnes Obel",
      "totalTracks": "27",
      "price": "",
      "albumImg": "https://i.scdn.co/image/ab67616d0000b273ed19f33217bec32cc4029a97",
      "releaseDate": "2011-05-02",
      "genre": null,
      "label": "Play It Again Sam"
  },
  {
      "id": "3",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "4",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "5",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "6",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "7",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "8",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "9",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "10",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "11",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "12",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "13",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "14",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "15",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "16",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "17",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "18",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  },
  {
      "id": "19",
      "name": "",
      "artist": "",
      "totalTracks": "",
      "price": "",
      "albumImg": "",
      "releaseDate": null,
      "genre": null,
      "label": null
  }
]
